### ISSUE TITLE
除自动选择IP外，无法手动设置ip地址

### ISSUE THREAD

**Issue by viistar** [qsaker/QtSwissArmyKnife#7]
使用过程中，例如TCP服务器端，服务器地址会自动识别出本地拥有的IP地址，但在windows 下不插网线设置的固定IP无法识别到，需要手动输入设置才行。modbus作TCP客户端时，主机地址是不应该为远程的IP地址，而不是本地的？

**Comment by daozhixiaoyao** [comment]
正常情况是这样的没错。
祝你一切顺利~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qsaker/QtSwissArmyKnife"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月25日(星期六) 晚上9:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qsaker/QtSwissArmyKnife] 除自动选择IP外，无法手动设置ip地址 (#7)





 
使用过程中，例如TCP服务器端，服务器地址会自动识别出本地拥有的IP地址，但在windows 下不插网线设置的固定IP无法识别到，需要手动输入设置才行。modbus作TCP客户端时，主机地址是不应该为远程的IP地址，而不是本地的？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by viistar** [comment]
好的
